# Generated by Django 4.2.4 on 2023-08-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demo_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('rollno', models.IntegerField(max_length=150, verbose_name='Roll Number')),
                ('city', models.CharField(choices=[('Pathankot', 'pathankot'), ('Jalandhar', 'Jalandhar'), ('Ludhiana', 'ludhiana')], max_length=150, verbose_name='City')),
                ('phone_number', models.IntegerField(max_length=10, verbose_name='Phone Number')),
            ],
        ),
    ]
